baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: de-DE
name: true-craft-boilerplate
primary: true
siteGroup: 068ede1e-b2fb-4fe1-a6f0-36f868f5fb5a # true-craft-boilerplate
sortOrder: 1
